Problem to be solved:

```
$ python main.py 
Traceback (most recent call last):
  File "C:\Users\Abdullah Faisal\Documents\nascon\nebula-testing\main.py", line 6, in <module>
    with open(file_path, 'w') as file:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Abdullah Faisal\\Documents\\nascon\\nebula-testing\\data\\example.txt'
```
